version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
  open-pull-requests-limit: 10
  labels:
  - type:dependency
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
  labels:
  - type:dependency
